#!/bin/bash
#PBS -N nno
#PBS -q normal
#PBS -o jsguo.out
#PBS -e jsguo.err
#PBS -l nodes=1:ppn=4
#PBS -l walltime=1000:00:00
##############################################################
cd $PBS_O_WORKDIR
export OMP_NUM_THREADS=1
export MKL_NUM_THREADS=1
export OPENBLAS_NUM_THREADS=1
#mpirun -np 64 /home/jsguo/bin/2-VASP/vasp.6.5.0_lic/bin/vasp_std
#####################################################
#mpirun -np 32 /home/jsguo/bin/2-VASP/vasp.6.5.0_lic_wannier/bin/vasp_std
################################################################
mpirun -np 4  ~/bin/wannier90_gfortran/wannier90.x wannier90

